version: "2"

run:
  timeout: 5m
  go: "1.25"
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: market-loader
  forbidigo:
    rules:
      - name: println
        pattern: ^println$
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - mnd
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl
        - funlen
        - gocyclo
        - lll
        - thelper
        - tparallel
    - path: cmd/
      linters:
        - mnd
        - goconst
        - dupl
        - funlen
        - gocyclo
        - lll
        - gosec
    - path: pkg/config/config.go
      linters:
        - gosec
    - path: cmd/loader-arch/main.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0