# Конфигурация для загрузки исторических данных Т-Инвестиции
# Согласно документации: https://developer.tbank.ru/invest/intro/intro/load_history
# Поддерживает 13 интервалов свечей: 1min, 2min, 3min, 5min, 10min, 15min, 30min,
#                                   1hour, 2hour, 4hour, 1day, 1week, 1month
#
# ИНСТРУКЦИЯ ПО НАСТРОЙКЕ:
# 1. Скопируйте этот файл в config/config.yaml
# 2. Замените "ВАШ_ТОКЕН" на реальный токен из личного кабинета Т-Инвестиции
# 3. Настройте параметры базы данных PostgreSQL
# 4. При необходимости измените настройки логирования и лимиты
#
# ВАЖНО: Не изменяйте dbname: "invest" - это значение жестко задано в коде

# Настройки базы данных PostgreSQL
database:
  host: "localhost"
  # host: "localhost"        # Локальная база
  # host: "192.168.1.100"   # Удаленная база по IP
  # host: "db.example.com"  # Удаленная база по домену
  port: 5432   # Стандартный порт PostgreSQL
  # Имя пользователя базы данных
  user: "t_invest_user" # Имя пользователя базы данных
  password: "your_secure_password" # Пароль пользователя базы данных
  dbname: "invest" # Имя базы данных. Это значение жестко задано в коде для совместимости с другими модулями.
  sslmode: "disable"
  # sslmode: "disable"       # Без SSL (для локальной разработки)
  # sslmode: "require"       # Требует SSL (для продакшена)
  # sslmode: "verify-full"   # Полная проверка SSL сертификата
  sslmode: "disable"

# Настройки T-invest Invest API
tinvest:
  token: "ВАШ_ТОКЕН" # Токен доступа к API. Получите в личном кабинете Т-Инвестиции: https://www.tinvest.ru/invest/
  endpoint: "invest-public-api.tinvest.ru:443"  # endpoint: "invest-public-api.tinvest.ru:443"      # Продакшен (реальные данные)
  # endpoint: "sandbox-invest-public-api.tinvest.ru:443"  # Песочница (тестовые данные)
  app_name: "t-invest-data-loader" # Название приложения (для идентификации в логах API)
  
# Настройки загрузки данных
loading:
  # Дата начала загрузки данных (формат: YYYY-MM-DD)
  # Если не указана, используется 5 лет назад от текущей даты
  # Примеры:
  # start_date: "2019-01-01"  # Загружать с 1 января 2019 года
  # start_date: "2020-03-01"  # Загружать с 1 марта 2020 года
  # start_date: "2022-01-01"  # Загружать с 1 января 2022 года
  # start_date: ""            # Использовать по умолчанию (5 лет назад)
  # start_date: "2015-01-01"  # Загружать с 1 января 2015 года (10 лет назад)
  start_date: "2017-01-01"
  
  # Лимиты загрузки данных (количество свечей за один запрос)
  # Эти значения установлены согласно ограничениям API Т-Инвестиции
  limits:
    # Минутные интервалы
    "1min":  1440  # 1 день (24 * 60 = 1440 минут)
    "2min":  720   # 1 день (24 * 30 = 720 интервалов)
    "3min":  48    # 1 день (24 * 2 = 48 интервалов)
    "5min":  2016  # 1 неделя (7 * 24 * 12 = 2016 интервалов)
    "10min": 1008  # 1 неделя (7 * 24 * 6 = 1008 интервалов)
    "15min": 2016  # 3 недели (21 * 24 * 4 = 2016 интервалов)
    "30min": 1008  # 3 недели (21 * 24 * 2 = 1008 интервалов)
    
    # Часовые интервалы
    "hour":  2160  # 3 месяца (90 * 24 = 2160 часов)
    "2hour": 1080  # 3 месяца (90 * 12 = 1080 интервалов)
    "4hour": 540   # 3 месяца (90 * 6 = 540 интервалов)
    
    # Дневные и более длинные интервалы
    "day":  1920   # 6 лет (6 * 365 = 2190, ограничено API до 1920)
    "week": 260    # 5 лет (5 * 52 = 260 недель)
    "month": 120   # 10 лет (10 * 12 = 120 месяцев)

  # Пауза между запросами (секунды)
  # Необходима для соблюдения лимитов API Т-Инвестиции
  # Примеры:
  # rate_limit_pause: 1    # Минимальная пауза (может вызвать ошибки API)
  # rate_limit_pause: 5    # Рекомендуемая пауза для обычной работы
  # rate_limit_pause: 10   # Более безопасная пауза для стабильности
  # rate_limit_pause: 30   # Максимальная пауза (медленно, но очень стабильно)
  rate_limit_pause: 5

# Настройки логирования
logging:
  # Уровень логирования
  # Доступные значения:
  # - "debug"   # Подробная отладочная информация (много логов)
  # - "info"    # Общая информация о работе (рекомендуется для продакшена)
  # - "warn"    # Только предупреждения и ошибки
  # - "error"   # Только ошибки
  # - "fatal"   # Только критические ошибки
  # Примеры:
  # level: "debug"  # Для разработки и отладки
  # level: "info"   # Для обычной работы
  # level: "warn"   # Для мониторинга только проблем
  level: "info"
  
  # Формат вывода логов
  # Доступные значения:
  # - "text"   # Человекочитаемый текст (рекомендуется для разработки)
  # - "json"   # Структурированный JSON (для систем мониторинга)
  # Примеры:
  # format: "text"  # Простой текстовый формат
  # format: "json"  # JSON для интеграции с ELK, Grafana и т.д.
  format: "text"
  
  # Дополнительные настройки логирования (опционально)
  # output: "stdout"     # Вывод в консоль (по умолчанию)
  # output: "file"       # Вывод в файл
  # output: "both"       # Вывод и в консоль, и в файл
  
  # Путь к файлу логов (если output: "file" или "both")
  # file_path: "./logs/t-invest-loader.log"
  
  # Максимальный размер файла логов в МБ (если output: "file" или "both")
  # max_file_size: 100
  
     # Количество файлов логов для ротации (если output: "file" или "both")
   # max_files: 5

# Настройки архивного загрузчика
archive:
  # Путь к временной директории для загрузки архивов
  # Если не указан, используется системная временная директория
  # Примеры:
  # temp_dir: "./temp"           # Относительный путь в папке проекта
  # temp_dir: "/tmp/t-invest"    # Абсолютный путь в Linux/Mac
  # temp_dir: "C:\\temp\\t-invest"  # Абсолютный путь в Windows
  # temp_dir: ""                 # Использовать системную временную директорию
  temp_dir: ""